version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://RootUser:resUtooR@gcp1.3ohjenb.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=GCP1
      - REDIS_URI=rediss://default:AVNS_gTMJXPyw1mnbIoXdtCt@gcp-redis-student-4ffb.aivencloud.com:19198
      